version: "3.12"
services:
  prod:
    build:
      context: .
      dockerfile: dockerfile
    container_name: mythica-prod

  dev:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: mythica-dev
    volumes:
      - .:/workspace
    tty: true
    stdin_open: true