[project]
name = "ecosystem"
version = "0.1.0"
description = "lib for simulation of fantasy worlds"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.9",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]