name: Run Tests

on:
  pull_request:
    branches:
      - dev
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dev image
        run: docker compose build dev

      - name: Run tests inside dev container
        run: docker compose run --rm dev uv run pytest